### ISSUE TITLE
Polishing the processing model section

### ISSUE THREAD

**Issue by domenic** [WICG/paint-timing#15]
- "Additions to the Paint Timing Spec" should be a different heading. This is the paint timing spec; talking about additions to it doesn't really make sense.
- "Paint or Render":
  - This section is redundant with the paragraph in the terminology section. I'm not sure which would be better to eliminate.
  - You should probably pick "paint" and stop mentioning "render"
  - You should make "paint" a definition (`<dfn>paint</dfn>`), and then you can later link to it (`[=paint=]`)
- "First Paint" / "First Contentful Paint":
  - Should link to Report Paint Timing
  - Should say paint instead of render, and link to the definition mentioned above
  - These should pass the name `"paint"` or `"first-contentful-paint"` as an argument to the report paint timing algorithm, as well as passing the timestamp.
- "Report Paint Timing"
  - This should be marked up as a definition in addition to a heading: `<h4 dfn>Report paint timing</h4>`. Then you can autolink to it.
  - The variable _newEntry_ should be marked up with `<var>`. In Bikeshed you can use the shorthand `|newEntry|`.
  - The strings should all be `<code>`ified.
  - Instead of doing "call stack inspection" to determine the name, (i.e., "depending on whether it is First Paint or First Contentful Paint"), this should take an argument with the name, as mentioned above.
  - Similarly, "timestamp recorded for corresponding render" should be passed in as an argument.
  - "Add the PerformanceEntry newEntry object." I think "Add the PerformanceEntry" is probably defined somewhere and should be linked to. It might take arguments.

**Comment by spanicker** [comment]
I've made the edits. PTAL?

**Comment by domenic** [comment]
Overall structural updates look good. My one question is whether you want to reuse the timestamp captured in https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering step 1, or get your own (twice) like the spec currently does. It seems like it might be out of sync with other algorithms if you capture your own, but I am not sure.

- Overall
  - More titlecase has crept in to headings; it should be sentence case
- Mark Paint Timing:
  - `update the rendering` should be `[=update the rendering=]` to get the autolink.
  - Strings should be `<code>`ified (in addition to having quotation marks)
  - `first paint` and `first contentful paint` should be `[=First Paint=]` and `[=First Contentful Paint=]` to get the autolink to their definitions.
  - The notes are probably redundant when you have proper links to the definitions.
- Report Paint Timing
  - name/entryType/startTime/duration should all be links, via syntax like `{{PerformanceEntry/name}}`.
  - The string `paint` needs quotation marks, not just `<code>`.
  - "Add the PerformanceEntry newEntry object." the word "object" seems redundant.

**Comment by spanicker** [comment]
We cannot reuse the timestamp from step 1 of "Update the rendering" as it doesn't capture the time spent in the rendering pipeline. For Paint Timing the goal is the measure the cost of the rendering pipeline.
(not sure how the other aglorithms are using the passed timestamp, I clicked through to a few and they don't seem to be using it)

I'll comment separately on the rest of your points.

**Comment by spanicker** [comment]
<<More titlecase has crept in to headings; it should be sentence case
"Paint Timing" is proper noun?

Address the rest. Thanks!
