### ISSUE TITLE
Transfer to WICG

### ISSUE THREAD

**Issue by igrigorik** [WICG/paint-timing#2]
@yoavweiss can you please help with this one?

**Comment by yoavweiss** [comment]
Gladly! :)

@tdresser - can you start a thread on WICG describing the feature and intent to move to WICG?
We can probably state overall room support for the feature at TPAC's webperfwg F2F.

The next step would be for you to transfer repo ownership to me, and I'll take it from there: move to WICG org and apply the required IPR git hooks.

**Comment by tdresser** [comment]
@spanicker will be driving this moving forward, so it probably makes sense for her to author the WICG thread.

I've initiated transferring the repo.

We're planning to rename the repo as we move it to WICG (paint-timing). I'm not sure what the best point to perform the rename is - we want to avoid having multiple kinds of stale links though.

**Comment by tdresser** [comment]
Renamed.

Shubhie, can you start a WICG thread?

**Comment by spanicker** [comment]
Yep.

**Comment by spanicker** [comment]
WICG thread: 
https://discourse.wicg.io/t/expose-first-paint-timing-in-performance-observer/1868

**Comment by yoavweiss** [comment]
Done!

**Comment by igrigorik** [comment]
\o/ .. thanks everyone!
